server:
  port: 80
  servlet:
    context-path: /blog
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,logback
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  #thymelea模板配置
  thymeleaf:
    cache: false
  #上传限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #QQ邮件
  mail:
    host: smtp.qq.com
    username: 自己邮箱
    password: 邮箱验证密码
    properties:
      mail:
        smtp:
          auth: true   # 需要验证登录名和密码
        starttls:
          enable: true    # 需要TLS认证 保证发送邮件安全验证
          required: true

#不同操作系统不同目录
file:
  uploadWindow: E:/photo
  uploadLinux: /home/chy/image



mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

